_wandb:
    value:
        cli_version: 0.24.0
        e:
            wrcydlsnl3bw1ueonjefn91uv1ruczdq:
                args:
                    - --pretrained_model_name_or_path=Manojb/stable-diffusion-2-1-base
                    - --instance_data_dir=/fs/nexus-scratch/ltahboub/CoupledSceneSampling/train_ready_data
                    - --output_dir=/fs/nexus-scratch/ltahboub/CoupledSceneSampling/mysore_palace_dreambooth_sd21
                    - --instance_prompt=a photo of sks palace
                    - --resolution=768
                    - --train_batch_size=1
                    - --gradient_accumulation_steps=1
                    - --learning_rate=5e-6
                    - --lr_scheduler=constant
                    - --lr_warmup_steps=0
                    - --max_train_steps=821
                    - --push_to_hub
                    - --report_to=wandb
                codePath: scripts/train_dreambooth.py
                codePathLocal: scripts/train_dreambooth.py
                cpu_count: 32
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "41922560000"
                        used: "24062996480"
                email: tahboub.laith11@gmail.com
                executable: /fs/nexus-scratch/ltahboub/CoupledSceneSampling/.venv/bin/python3
                git:
                    commit: afa41786fae8fd31f3b9f1562e7102a9db28c3fd
                    remote: git@github.com:LaithTahboub/CoupledSceneSampling.git
                gpu: NVIDIA RTX A6000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-5c54030d-0077-ed80-a6e6-e11f672b022f
                host: vulcan29.umiacs.umd.edu
                memory:
                    total: "269764759552"
                os: Linux-4.18.0-553.89.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /fs/nexus-scratch/ltahboub/CoupledSceneSampling/scripts/train_dreambooth.py
                python: CPython 3.10.19
                root: /fs/nexus-scratch/ltahboub/CoupledSceneSampling
                slurm:
                    cluster_name: nexus
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: vulcan-jbhuang
                    job_cpus_per_node: "1"
                    job_end_time: "1768749477"
                    job_gid: "17811"
                    job_gpus: "0"
                    job_id: "6140723"
                    job_name: finetuning_dreambooth
                    job_nodelist: vulcan29
                    job_num_nodes: "1"
                    job_partition: vulcan-ampere
                    job_qos: vulcan-medium
                    job_start_time: "1768663077"
                    job_uid: "17811"
                    job_user: ltahboub
                    jobid: "6140723"
                    localid: "0"
                    mem_per_node: "49152"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: vulcan29
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /fs/nexus-scratch/ltahboub/CoupledSceneSampling
                    submit_host: vulcan24.umiacs.umd.edu
                    task_pid: "3210184"
                    tasks_per_node: "1"
                    topology_addr: vulcan29
                    topology_addr_pattern: node
                startedAt: "2026-01-17T15:18:36.029293Z"
                writerId: wrcydlsnl3bw1ueonjefn91uv1ruczdq
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "3":
                - 2
                - 61
            "4": 3.10.19
            "5": 0.24.0
            "6": 4.57.5
            "12": 0.24.0
            "13": linux-x86_64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
adam_weight_decay:
    value: 0.01
allow_tf32:
    value: false
center_crop:
    value: false
checkpointing_steps:
    value: 500
checkpoints_total_limit:
    value: null
class_data_dir:
    value: null
class_labels_conditioning:
    value: null
class_prompt:
    value: null
dataloader_num_workers:
    value: 0
enable_xformers_memory_efficient_attention:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
hub_model_id:
    value: null
hub_token:
    value: null
instance_data_dir:
    value: /fs/nexus-scratch/ltahboub/CoupledSceneSampling/train_ready_data
instance_prompt:
    value: a photo of sks palace
learning_rate:
    value: 5e-06
local_rank:
    value: -1
logging_dir:
    value: logs
lr_num_cycles:
    value: 1
lr_power:
    value: 1
lr_scheduler:
    value: constant
lr_warmup_steps:
    value: 0
max_grad_norm:
    value: 1
max_train_steps:
    value: 821
mixed_precision:
    value: null
num_class_images:
    value: 100
num_train_epochs:
    value: 1
num_validation_images:
    value: 4
offset_noise:
    value: false
output_dir:
    value: /fs/nexus-scratch/ltahboub/CoupledSceneSampling/mysore_palace_dreambooth_sd21
pre_compute_text_embeddings:
    value: false
pretrained_model_name_or_path:
    value: Manojb/stable-diffusion-2-1-base
prior_generation_precision:
    value: null
prior_loss_weight:
    value: 1
push_to_hub:
    value: true
report_to:
    value: wandb
resolution:
    value: 768
resume_from_checkpoint:
    value: null
revision:
    value: null
sample_batch_size:
    value: 4
scale_lr:
    value: false
seed:
    value: null
set_grads_to_none:
    value: false
skip_save_text_encoder:
    value: false
snr_gamma:
    value: null
text_encoder_use_attention_mask:
    value: false
tokenizer_max_length:
    value: null
tokenizer_name:
    value: null
train_batch_size:
    value: 1
train_text_encoder:
    value: false
use_8bit_adam:
    value: false
validation_prompt:
    value: null
validation_scheduler:
    value: DPMSolverMultistepScheduler
validation_steps:
    value: 100
variant:
    value: null
with_prior_preservation:
    value: false
