_wandb:
    value:
        cli_version: 0.24.0
        e:
            1evp7gsxqikg6x9irfff0457kbh57yvw:
                args:
                    - --pretrained_model_name_or_path=stable-diffusion-v1-5/stable-diffusion-v1-5
                    - --instance_data_dir=/fs/nexus-scratch/ltahboub/CoupledSceneSampling/test_final/Mysore_Palace/images/commons/East_side_of_the_Mysore_Palace/0/pictures
                    - --output_dir=/fs/nexus-scratch/ltahboub/CoupledSceneSampling/mysore_palace_dreambooth_sd15
                    - --instance_prompt=a photo of sks landmark
                    - --resolution=512
                    - --train_batch_size=2
                    - --gradient_accumulation_steps=1
                    - --learning_rate=2e-6
                    - --lr_scheduler=constant
                    - --lr_warmup_steps=0
                    - --max_train_steps=2000
                    - --report_to=wandb
                codePath: scripts/train_dreambooth.py
                codePathLocal: scripts/train_dreambooth.py
                cpu_count: 32
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "41922560000"
                        used: "22645424128"
                email: tahboub.laith11@gmail.com
                executable: /fs/nexus-scratch/ltahboub/CoupledSceneSampling/.venv/bin/python3
                git:
                    commit: 7b9f36284c7f4313c411596d350f98caa3adfa17
                    remote: git@github.com:LaithTahboub/CoupledSceneSampling.git
                gpu: NVIDIA RTX A6000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-aa127bc2-2adf-e5fa-88d6-d1eb5febe7fd
                host: vulcan31.umiacs.umd.edu
                memory:
                    total: "269764751360"
                os: Linux-4.18.0-553.89.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /fs/nexus-scratch/ltahboub/CoupledSceneSampling/scripts/train_dreambooth.py
                python: CPython 3.10.19
                root: /fs/nexus-scratch/ltahboub/CoupledSceneSampling
                slurm:
                    cluster_name: nexus
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: vulcan-jbhuang
                    job_cpus_per_node: "1"
                    job_end_time: "1768831760"
                    job_gid: "17811"
                    job_gpus: "1"
                    job_id: "6154421"
                    job_name: finetuning_dreambooth
                    job_nodelist: vulcan31
                    job_num_nodes: "1"
                    job_partition: vulcan-ampere
                    job_qos: vulcan-medium
                    job_start_time: "1768745360"
                    job_uid: "17811"
                    job_user: ltahboub
                    jobid: "6154421"
                    localid: "0"
                    mem_per_node: "49152"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: vulcan31
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /fs/nexus-scratch/ltahboub/CoupledSceneSampling
                    submit_host: vulcan24.umiacs.umd.edu
                    task_pid: "820868"
                    tasks_per_node: "1"
                    topology_addr: vulcan31
                    topology_addr_pattern: node
                startedAt: "2026-01-18T14:09:58.194986Z"
                writerId: 1evp7gsxqikg6x9irfff0457kbh57yvw
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "3":
                - 2
                - 61
            "4": 3.10.19
            "5": 0.24.0
            "6": 4.57.5
            "12": 0.24.0
            "13": linux-x86_64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
adam_weight_decay:
    value: 0.01
allow_tf32:
    value: false
center_crop:
    value: false
checkpointing_steps:
    value: 500
checkpoints_total_limit:
    value: null
class_data_dir:
    value: null
class_labels_conditioning:
    value: null
class_prompt:
    value: null
dataloader_num_workers:
    value: 0
enable_xformers_memory_efficient_attention:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
hub_model_id:
    value: null
hub_token:
    value: null
instance_data_dir:
    value: /fs/nexus-scratch/ltahboub/CoupledSceneSampling/test_final/Mysore_Palace/images/commons/East_side_of_the_Mysore_Palace/0/pictures
instance_prompt:
    value: a photo of sks landmark
learning_rate:
    value: 2e-06
local_rank:
    value: -1
logging_dir:
    value: logs
lr_num_cycles:
    value: 1
lr_power:
    value: 1
lr_scheduler:
    value: constant
lr_warmup_steps:
    value: 0
max_grad_norm:
    value: 1
max_train_steps:
    value: 2000
mixed_precision:
    value: null
num_class_images:
    value: 100
num_train_epochs:
    value: 84
num_validation_images:
    value: 4
offset_noise:
    value: false
output_dir:
    value: /fs/nexus-scratch/ltahboub/CoupledSceneSampling/mysore_palace_dreambooth_sd15
pre_compute_text_embeddings:
    value: false
pretrained_model_name_or_path:
    value: stable-diffusion-v1-5/stable-diffusion-v1-5
prior_generation_precision:
    value: null
prior_loss_weight:
    value: 1
push_to_hub:
    value: false
report_to:
    value: wandb
resolution:
    value: 512
resume_from_checkpoint:
    value: null
revision:
    value: null
sample_batch_size:
    value: 4
scale_lr:
    value: false
seed:
    value: null
set_grads_to_none:
    value: false
skip_save_text_encoder:
    value: false
snr_gamma:
    value: null
text_encoder_use_attention_mask:
    value: false
tokenizer_max_length:
    value: null
tokenizer_name:
    value: null
train_batch_size:
    value: 2
train_text_encoder:
    value: false
use_8bit_adam:
    value: false
validation_prompt:
    value: null
validation_scheduler:
    value: DPMSolverMultistepScheduler
validation_steps:
    value: 100
variant:
    value: null
with_prior_preservation:
    value: false
